version: '3.8'

services:
  db:
    container_name: stayspot_db
    image: postgres
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: postgresdb
      POSTGRES_DB: postgresdb
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_stayspot:/var/lib/postgresql/data_stayspot
volumes:
  db_data_stayspot: